from . import digital_performance
from . import digital_task
from . import actions_common
from . import qualitative_analysis
from . import other_works
from . import academic_tracker
from . import academic_performance
from . import hr_employee
from . import marketing_performance
from . import employee_performance
from . import sales_tracker
from . import academic_data
from . import accounts_tracker